//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class vahiniEntities2 : DbContext
    {
        public vahiniEntities2()
            : base("name=vahiniEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual ObjectResult<sp_driver_Result> sp_driver(Nullable<int> routeId, string command)
        {

            var routeIdParameter = routeId.HasValue ?
                new ObjectParameter("routeId", routeId) :
                new ObjectParameter("routeId", typeof(int));

            var commandParameter = command != null ?
                new ObjectParameter("command", command) :
                new ObjectParameter("command", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_driver_Result>("sp_driver", routeIdParameter, commandParameter);
        }

    }
}
